---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 杜宇翔.
--- DateTime: 2025/5/31 13:49
---

---1参数列表
---1.1。由于redis中的优惠卷是动态的，所以优惠卷id需要传递

local voucherId = ARGV[1]

---1.2. 用户id
local userId = ARGV[2]
---2.数据key
---2.1库存key
local stockKey = "seckill:stock:" .. voucherId
---2.2订单key
local orderKey = "seckill:order:" .. userId
---3脚本
---3。1库存是否充足，不足返回1

if(tonumber(redis.call('get',stockKey)) <= 0) then
    return 1;
end

---3.2用户是否下单，若下过单返回2
if(redis.call('sismember',orderKey,userId)==1) then
    return 2
end
---3.3扣掉库存
redis.call('incrby',stockKey,-1)
---3.4将userId存入当前优惠卷的set集合，返回0

redis.call('sadd',orderKey,userId)

return 0