---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 杜宇翔.
--- DateTime: 2025/5/29 17:34
---

local value = redis.call('get', KEYS[1])

local current = ARGV[1]

if(value==current) then
    return redis.call('del',KEYS[1])
end

return 0